Ex 18 - 

(Programa)

remove(X,[X|XS],XS).

remove(X,[Y|YS],[Y|G]):-
    remove(X,YS,G).

permutacao([],[]).
permutacao(AS,[B|CS]):- remove(B,AS,BS),permutacao(BS,CS).

(Consulta)

?- permutacao([a,m,o,r],A).
X = [a, m, o, r]
X = [a, m, r, o]
X = [a, o, m, r]
X = [a, o, r, m]
X = [a, r, m, o]
X = [a, r, o, m]
X = [m, a, o, r]
X = [m, a, r, o]
X = [m, o, a, r]
X = [m, o, r, a]
X = [m, r, a, o]
X = [m, r, o, a]
X = [o, a, m, r]
X = [o, a, r, m]
X = [o, m, a, r]
X = [o, m, r, a]
X = [o, r, a, m]
X = [o, r, m, a]
X = [r, a, m, o]
X = [r, a, o, m]
X = [r, m, a, o]
X = [r, m, o, a]
X = [r, o, a, m]
X = [r, o, m, a]

?- permutacao([carlos,rose,sergio,adriano,fabiola],A).
A = [carlos, rose, sergio, adriano, fabiola]
A = [carlos, rose, sergio, fabiola, adriano]
A = [carlos, rose, adriano, sergio, fabiola]
A = [carlos, rose, adriano, fabiola, sergio]
A = [carlos, rose, fabiola, sergio, adriano]
A = [carlos, rose, fabiola, adriano, sergio]
A = [carlos, sergio, rose, adriano, fabiola]
A = [carlos, sergio, rose, fabiola, adriano]
A = [carlos, sergio, adriano, rose, fabiola]
A = [carlos, sergio, adriano, fabiola, rose]
A = [carlos, sergio, fabiola, rose, adriano]
A = [carlos, sergio, fabiola, adriano, rose]
A = [carlos, adriano, rose, sergio, fabiola]
A = [carlos, adriano, rose, fabiola, sergio]
A = [carlos, adriano, sergio, rose, fabiola]
A = [carlos, adriano, sergio, fabiola, rose]
A = [carlos, adriano, fabiola, rose, sergio]
A = [carlos, adriano, fabiola, sergio, rose]
A = [carlos, fabiola, rose, sergio, adriano]
A = [carlos, fabiola, rose, adriano, sergio]
A = [carlos, fabiola, sergio, rose, adriano]
A = [carlos, fabiola, sergio, adriano, rose]
A = [carlos, fabiola, adriano, rose, sergio]
A = [carlos, fabiola, adriano, sergio, rose]
A = [rose, carlos, sergio, adriano, fabiola]
A = [rose, carlos, sergio, fabiola, adriano]
A = [rose, carlos, adriano, sergio, fabiola]
A = [rose, carlos, adriano, fabiola, sergio]
A = [rose, carlos, fabiola, sergio, adriano]
A = [rose, carlos, fabiola, adriano, sergio]
A = [rose, sergio, carlos, adriano, fabiola]
A = [rose, sergio, carlos, fabiola, adriano]
A = [rose, sergio, adriano, carlos, fabiola]
A = [rose, sergio, adriano, fabiola, carlos]
A = [rose, sergio, fabiola, carlos, adriano]
A = [rose, sergio, fabiola, adriano, carlos]
A = [rose, adriano, carlos, sergio, fabiola]
A = [rose, adriano, carlos, fabiola, sergio]
A = [rose, adriano, sergio, carlos, fabiola]
A = [rose, adriano, sergio, fabiola, carlos]
A = [rose, adriano, fabiola, carlos, sergio]
A = [rose, adriano, fabiola, sergio, carlos]
A = [rose, fabiola, carlos, sergio, adriano]
A = [rose, fabiola, carlos, adriano, sergio]
A = [rose, fabiola, sergio, carlos, adriano]
A = [rose, fabiola, sergio, adriano, carlos]
A = [rose, fabiola, adriano, carlos, sergio]
A = [rose, fabiola, adriano, sergio, carlos]
A = [sergio, carlos, rose, adriano, fabiola]
A = [sergio, carlos, rose, fabiola, adriano]
A = [sergio, carlos, adriano, rose, fabiola]
A = [sergio, carlos, adriano, fabiola, rose]
A = [sergio, carlos, fabiola, rose, adriano]
A = [sergio, carlos, fabiola, adriano, rose]
A = [sergio, rose, carlos, adriano, fabiola]
A = [sergio, rose, carlos, fabiola, adriano]
A = [sergio, rose, adriano, carlos, fabiola]
A = [sergio, rose, adriano, fabiola, carlos]
A = [sergio, rose, fabiola, carlos, adriano]
A = [sergio, rose, fabiola, adriano, carlos]
A = [sergio, adriano, carlos, rose, fabiola]
A = [sergio, adriano, carlos, fabiola, rose]
A = [sergio, adriano, rose, carlos, fabiola]
A = [sergio, adriano, rose, fabiola, carlos]
A = [sergio, adriano, fabiola, carlos, rose]
A = [sergio, adriano, fabiola, rose, carlos]
A = [sergio, fabiola, carlos, rose, adriano]
A = [sergio, fabiola, carlos, adriano, rose]
A = [sergio, fabiola, rose, carlos, adriano]
A = [sergio, fabiola, rose, adriano, carlos]
A = [sergio, fabiola, adriano, carlos, rose]
A = [sergio, fabiola, adriano, rose, carlos]
A = [adriano, carlos, rose, sergio, fabiola]
A = [adriano, carlos, rose, fabiola, sergio]
A = [adriano, carlos, sergio, rose, fabiola]
A = [adriano, carlos, sergio, fabiola, rose]
A = [adriano, carlos, fabiola, rose, sergio]
A = [adriano, carlos, fabiola, sergio, rose]
A = [adriano, rose, carlos, sergio, fabiola]
A = [adriano, rose, carlos, fabiola, sergio]
A = [adriano, rose, sergio, carlos, fabiola]
A = [adriano, rose, sergio, fabiola, carlos]
A = [adriano, rose, fabiola, carlos, sergio]
A = [adriano, rose, fabiola, sergio, carlos]
A = [adriano, sergio, carlos, rose, fabiola]
A = [adriano, sergio, carlos, fabiola, rose]
A = [adriano, sergio, rose, carlos, fabiola]
A = [adriano, sergio, rose, fabiola, carlos]
A = [adriano, sergio, fabiola, carlos, rose]
A = [adriano, sergio, fabiola, rose, carlos]
A = [adriano, fabiola, carlos, rose, sergio]
A = [adriano, fabiola, carlos, sergio, rose]
A = [adriano, fabiola, rose, carlos, sergio]
A = [adriano, fabiola, rose, sergio, carlos]
A = [adriano, fabiola, sergio, carlos, rose]
A = [adriano, fabiola, sergio, rose, carlos]
A = [fabiola, carlos, rose, sergio, adriano]
A = [fabiola, carlos, rose, adriano, sergio]
A = [fabiola, carlos, sergio, rose, adriano]
A = [fabiola, carlos, sergio, adriano, rose]
A = [fabiola, carlos, adriano, rose, sergio]
A = [fabiola, carlos, adriano, sergio, rose]
A = [fabiola, rose, carlos, sergio, adriano]
A = [fabiola, rose, carlos, adriano, sergio]
A = [fabiola, rose, sergio, carlos, adriano]
A = [fabiola, rose, sergio, adriano, carlos]
A = [fabiola, rose, adriano, carlos, sergio]
A = [fabiola, rose, adriano, sergio, carlos]
A = [fabiola, sergio, carlos, rose, adriano]
A = [fabiola, sergio, carlos, adriano, rose]
A = [fabiola, sergio, rose, carlos, adriano]
A = [fabiola, sergio, rose, adriano, carlos]
A = [fabiola, sergio, adriano, carlos, rose]
A = [fabiola, sergio, adriano, rose, carlos]
A = [fabiola, adriano, carlos, rose, sergio]
A = [fabiola, adriano, carlos, sergio, rose]
A = [fabiola, adriano, rose, carlos, sergio]
A = [fabiola, adriano, rose, sergio, carlos]
A = [fabiola, adriano, sergio, carlos, rose]
A = [fabiola, adriano, sergio, rose, carlos]